(() => {
  const modeNames={flick:'REFLEX FLICK',strafe:'STRAFE LOCK',micro:'MICROSHOT',chaos:'CHAOS'};
  const skins=['creeper','zombie','skeleton','slime','enderman','away','skin2','skin3','skin4','skin5'];
  const s={active:false,paused:false,lockedOnce:false,mode:'flick',duration:60,time:60,hits:0,shots:0,streak:0,bestStreak:0,reactions:[],spawnAt:0,last:0,yaw:0,pitch:0,vyaw:0,vpitch:0,frame:0};
  const cfg={speed:100,size:100,lifetime:2,sensitivity:100,fov:90};
  const el={layer:()=>document.getElementById('gameLayer'),world:()=>document.querySelector('.game-world'),target:()=>document.getElementById('target'),hint:()=>document.getElementById('lockHint')};
  const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const mouseStep=()=>{const n=clamp(cfg.sensitivity,0,200)/200,f=n*.6+.2;return f*f*f*8*.15};
  const selectedSkin=()=>AimBackend.state.profile?.selected_target||AimRanks.getGuest().selected_target||'creeper';
  function applySkin(){const t=el.target();skins.forEach(x=>t.classList.remove('skin-'+x));t.classList.add('skin-'+selectedSkin())}
  function render(){const vfov=cfg.fov*.56,x=50+s.yaw/(cfg.fov/2)*50,y=50+s.pitch/(vfov/2)*50;const t=el.target();t.style.left=x+'%';t.style.top=y+'%'}
  function spawn(){const micro=s.mode==='micro',yr=micro?12:38,pr=micro?7:19;s.yaw=rand(-yr,yr);s.pitch=rand(-pr,pr);s.spawnAt=performance.now();const base=(s.mode==='chaos'?18:12)*(cfg.speed/100);s.vyaw=(Math.random()<.5?-1:1)*base;s.vpitch=s.mode==='chaos'?(Math.random()<.5?-1:1)*base*.55:0;render()}
  const avgReaction=()=>s.reactions.length?Math.round(s.reactions.reduce((a,b)=>a+b,0)/s.reactions.length):null;
  function ui(){const calc=AimRanks.computeRun({mode:s.mode,hits:s.hits,shots:s.shots,bestStreak:s.bestStreak,avgReaction:avgReaction()});document.getElementById('hudScore').textContent=calc.score.toLocaleString('de-DE');document.getElementById('hudAccuracy').textContent=(s.shots?s.hits/s.shots*100:100).toFixed(0)+'%';document.getElementById('hudReaction').textContent=s.reactions.length?Math.round(s.reactions.at(-1))+'ms':'—';document.getElementById('hudStreak').textContent='×'+s.streak;document.getElementById('hudTime').textContent=Math.max(0,s.time).toFixed(1)}
  function requestLock(){el.world()?.requestPointerLock?.();if(el.hint())el.hint().classList.add('show')}
  function start(mode=s.mode,duration=+document.getElementById('duration').value){Object.assign(s,{active:true,paused:false,lockedOnce:false,mode,duration,time:duration,hits:0,shots:0,streak:0,bestStreak:0,reactions:[],last:performance.now()});applySkin();const t=el.target();t.style.setProperty('--size',(cfg.size*(mode==='micro'?.7:1))/100);t.classList.add('visible');document.body.classList.add('in-game');el.layer().classList.add('active');el.layer().setAttribute('aria-hidden','false');document.getElementById('hudMode').textContent=modeNames[mode];spawn();ui();cancelAnimationFrame(s.frame);s.frame=requestAnimationFrame(loop);setTimeout(requestLock,20)}
  function isCrosshairOnTarget(){const w=el.world().getBoundingClientRect(),t=el.target().getBoundingClientRect(),cx=w.left+w.width/2,cy=w.top+w.height/2,tx=t.left+t.width/2,ty=t.top+t.height/2;return Math.hypot(tx-cx,ty-cy)<=Math.max(t.width,t.height)*.52}
  function shoot(){if(!s.active||s.paused)return;s.shots++;if(isCrosshairOnTarget()){s.hits++;s.streak++;s.bestStreak=Math.max(s.bestStreak,s.streak);const reaction=performance.now()-s.spawnAt;if(reaction>55&&reaction<10000)s.reactions.push(reaction);const marker=document.getElementById('hitMarker');marker.style.left='50%';marker.style.top='50%';marker.classList.remove('pop');void marker.offsetWidth;marker.classList.add('pop');const t=el.target();t.classList.remove('hit');void t.offsetWidth;t.classList.add('hit');spawn()}else{s.streak=0;const w=el.world();w.classList.remove('miss');void w.offsetWidth;w.classList.add('miss')}ui()}
  function move(dt){if(s.mode==='flick'||s.mode==='micro'){if((performance.now()-s.spawnAt)/1000>cfg.lifetime){s.streak=0;spawn()}return}const boost=1+Math.min(.8,s.streak*.018);s.yaw+=s.vyaw*dt*boost;s.pitch+=s.vpitch*dt*boost;if(s.yaw<-42||s.yaw>42){s.vyaw*=-1;s.yaw=clamp(s.yaw,-42,42)}if(s.mode==='chaos'&&(s.pitch<-20||s.pitch>20)){s.vpitch*=-1;s.pitch=clamp(s.pitch,-20,20)}if(s.mode==='strafe')s.pitch=Math.sin(performance.now()/430)*4.5;render()}
  function loop(now){if(!s.active)return;const dt=Math.min(.05,(now-s.last)/1000);s.last=now;if(!s.paused){s.time-=dt;move(dt);ui();if(s.time<=0){finish();return}}s.frame=requestAnimationFrame(loop)}
  function pause(exit=true){if(!s.active||s.paused)return;s.paused=true;document.getElementById('pauseOverlay').classList.add('active');if(exit&&document.pointerLockElement)document.exitPointerLock?.()}
  function resume(){if(!s.active)return;s.paused=false;s.last=performance.now();document.getElementById('pauseOverlay').classList.remove('active');requestLock()}
  function quit(){s.active=false;s.paused=false;cancelAnimationFrame(s.frame);if(document.pointerLockElement)document.exitPointerLock?.();document.getElementById('pauseOverlay').classList.remove('active');el.layer().classList.remove('active');document.body.classList.remove('in-game');el.target().classList.remove('visible')}
  async function finish(){s.active=false;cancelAnimationFrame(s.frame);if(document.pointerLockElement)document.exitPointerLock?.();el.target().classList.remove('visible');const run={mode:s.mode,duration:s.duration,hits:s.hits,shots:s.shots,bestStreak:s.bestStreak,avgReaction:avgReaction()};let result=AimRanks.computeRun(run),oldTier,newTier,totalRp,promoted=false,coinsGain=result.coinsGain,totalCoins;const accountRun=!!AimBackend.state.session;if(accountRun){try{const remote=await AimBackend.submitRun(run);result={...result,...remote};totalRp=remote.newRp;oldTier=remote.oldTier;newTier=remote.tier;promoted=remote.promoted;coinsGain=remote.coinsGain;totalCoins=remote.newCoins}catch(e){window.AimUI?.toast('Sync fehlgeschlagen: '+(e.message||e)+' — RP wurde nicht verworfen, bitte erneut einloggen.','error');totalRp=Number(AimBackend.state.profile?.rp||0);oldTier=newTier=AimRanks.byRp(totalRp).name;promoted=false;result.rpGain=0;coinsGain=0}}else{const g=AimRanks.getGuest(),old=AimRanks.byRp(g.rp).name,now=Math.min(AimRanks.MAX_RP,g.rp+result.rpGain),sessions=(g.sessions||0)+1,newAvg=run.avgReaction==null?g.avg_reaction:(g.avg_reaction==null?run.avgReaction:Math.round((g.avg_reaction*Math.min(g.sessions||0,19)+run.avgReaction)/Math.min(sessions,20)));Object.assign(g,{rp:now,coins:(g.coins||0)+result.coinsGain,best_score:Math.max(g.best_score||0,result.score),total_hits:(g.total_hits||0)+s.hits,total_shots:(g.total_shots||0)+s.shots,sessions,best_streak:Math.max(g.best_streak||0,s.bestStreak),avg_reaction:newAvg});AimRanks.saveGuest(g);totalRp=now;totalCoins=g.coins;oldTier=old;newTier=AimRanks.byRp(now).name;promoted=oldTier!==newTier}el.layer().classList.remove('active');document.body.classList.remove('in-game');window.AimUI?.showResults({...run,...result,totalRp,totalCoins,coinsGain,oldTier,newTier,promoted});window.AimUI?.refreshProfileUI()}
  function setConfig(next){Object.assign(cfg,next)}
  document.addEventListener('DOMContentLoaded',()=>{const h=document.createElement('div');h.id='lockHint';h.className='lock-hint';h.innerHTML='<b>CLICK TO LOCK MOUSE</b><span>Move the camera like Minecraft • Left click to hit • ESC pauses</span>';el.layer().append(h);el.world().addEventListener('click',()=>{if(document.pointerLockElement!==el.world()){requestLock();return}shoot()});el.target().style.pointerEvents='none';document.addEventListener('mousemove',e=>{if(!s.active||s.paused||document.pointerLockElement!==el.world())return;const step=mouseStep();s.yaw-=e.movementX*step;s.pitch-=e.movementY*step;render()});document.addEventListener('pointerlockchange',()=>{const locked=document.pointerLockElement===el.world();if(locked){s.lockedOnce=true;h.classList.remove('show')}else if(s.active&&s.lockedOnce&&!s.paused)pause(false)});document.getElementById('pauseButton').onclick=()=>pause();document.getElementById('resumeButton').onclick=resume;document.getElementById('quitRunButton').onclick=()=>{quit();window.AimUI?.showView('train')};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&s.active&&!s.paused)pause(false)})});
  window.AimGame={state:s,cfg,start,pause,resume,quit,setConfig,modeNames,applySkin};
})();